version: '3'

networks:
    factorytx-net:
        driver: bridge

volumes:
    send-log-data-volume:
        driver: local
    receive-log-data-volume:
        driver: local
    data-buffer-volume:
        driver: local
    pip-cache:
        driver: local

services:
    factorytx_send:
        container_name: factorytx_send
        hostname: factorytx_send
        image: sightmachine/factorytx
        networks:
            - factorytx-net
        build:
            context: /opt/sightmachine/factorytx
            dockerfile: Dockerfile
        tty: true
        volumes:
            # - ./factorytx/pipelines/conf.d/int_send:/opt/sightmachine/factorytx/factorytx/pipelines/conf.d/
            - ./:/opt/sightmachine/factorytx/
            - data-buffer-volume:/var/spool/sightmachine/factorytx/
            - send-log-data-volume:/var/log/sightmachine/factorytx/
            - pip-cache:/root/.cache/pip/

    factorytx_receive:
        container_name: factorytx_receive
        hostname: factorytx_receive
        image: sightmachine/factorytx
        networks:
            - factorytx-net
        build:
            context: /opt/sightmachine/factorytx
            dockerfile: Dockerfile
        tty: true
        volumes:
            # - ./factorytx/pipelines/conf.d/int_receive:/opt/sightmachine/factorytx/factorytx/pipelines/conf.d/
            - ./:/opt/sightmachine/factorytx/
            - data-buffer-volume:/var/spool/sightmachine/factorytx/
            - receive-log-data-volume:/var/log/sightmachine/factorytx/
            - pip-cache:/root/.cache/pip/

    simpledata:
        container_name: simpledata
        image: sightmachine/simpledata
        hostname: simpledata
        build:
            context: ../SimpleData/
            dockerfile: Dockerfile
        stdin_open: true
        command: /bin/bash
        working_dir: /opt/sightmachine/simpledata
        volumes:
            - /opt/sightmachine/simpledata/plugins/conf.d:/opt/sightmachine/simpledata/plugins/conf.d
            - /opt/sightmachine/simpledata:/opt/sightmachine/simpledata
            - /opt/sightmachine/databuffer:/var/spool/sightmachine/simpledata/
